#!/usr/bin/env bash

#Create VPC

VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" \
--region ap-southeast-4 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]' \
--query 'Vpc.VpcId' \
--output text)

echo $VPC_ID

#CREATE SUBNET
SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID --cidr-block 172.1.0.0/20 \
--query 'Subnet.SubnetId' \
--output text)
echo $SUBNET_ID

aws ec2 modify-subnet-attribute \
  --subnet-id $SUBNET_ID \
  --map-public-ip-on-launch

# CREATE IGW
GATEWAY_ID=$(aws ec2 create-internet-gateway \
--query 'InternetGateway.InternetGatewayId' \
--output text)
echo $GATEWAY_ID

# Attach IGW to VPC

aws ec2 attach-internet-gateway --internet-gateway-id $GATEWAY_ID --vpc-id $VPC_ID
echo 'Attached IGW to Vpc'

# Create Route table
RT_ID=$(aws ec2 create-route-table \
--vpc-id $VPC_ID \
--region ap-southeast-4 \
--query 'RouteTable.RouteTableId' \
--output text)
echo "Route Table: $RT_ID"

# Link IGW to the public internet
aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block "0.0.0.0/0" \
--gateway-id $GATEWAY_ID \
--region ap-southeast-4

# Associate subnet 
aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--region ap-southeast-4