#!/usr/bin/env bash

#Create VPC

VPC_ID=$(aws ec2 create-vpc --cidr-block "172.1.0.0/16" \
--region ap-southeast-4 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=my-vpc-3}]' \
--query 'Vpc.VpcId' \
--output text)

echo $VPC_ID
#CREATE SUBNET

# Connect Subnet to vpc

# CREATE IGW

# Attach IGW to VPC
 
# Create Route table

# Link IGW to the public internet

# Associate subnet 