#!/usr/bin/env bash

# Check for vpc id argument
if [ -z "$1" ]; then
    echo "Argument not provided."
else 
    export VPC_ID="$1"
fi

# detach igw

# delete igw

#delete vpc w id
aws ec2 delete-vpc --vpc-id $VPC_ID