#!/usr/bin/env bash

set -e

# Check for bucket name
if [ -z "$1" ]; then
    echo "There needs to be a bucket name "
    exit 1
fi


# Check for file name
if [ -z "$2" ]; then
    echo "There needs to be a bucket name "
    exit 1
fi

BUCKET_NAME=$1
FILE_NAME=$2
OBJECT_KEY=$(basename "$FILE_NAME")

tree $OUTPUT_DIR

aws s3api put-object --bucket $BUCKET_NAME --body $FILE_NAME --key $OBJECT_KEY