#! /usr/bin/env bash

echo " --- deploy s3 bucket via CFN --- "

STACK_NAME="learning-cfn-dididididid"
S3_region="ap-southeast-4"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--stack-name $STACK_NAME \
--region $S3_region
